import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Unbrewed API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            height: "90vh",
            fontFamily: "monospace",
          }}
        >
          <h1>Unbrewed API</h1>
          <p>
            this is a micro-site for exposing api to make unbrewed-p2p more
            useful
          </p>
        </div>
      </main>
    </>
  );
}
